server:
  port: 8994

spring:
  application:
    name: luck-report-agent
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/luck_report_agent?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.luck.agent.entity


logging:
  level:
    root: INFO
    com.luck.agent: DEBUG
