server:
  port: 8994

spring:
  application:
    name: luck-report-agent
  datasource:
    url: jdbc:mysql://localhost:3306/luck_report_agent?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      pool-name: maindb-pool

luck-report:
  datasource:
    pgvector:
      url: jdbc:postgresql://localhost:5432/postgres?currentSchema=luck_report_vector
      username: postgres
      password: root
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 5

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.luck.agent.entity

logging:
  level:
    root: INFO
    com.luck.agent: DEBUG
