spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=luck_report_vector
    driver-class-name: org.postgresql.Driver

luck-report:
  # 请求前缀
  servletPrefix: report
  # 报表存储路径
  fileStoreDir: E:/luckStudio/IO/report
  # 调试日志
  debug: true
  # 自动扫描组件
  autoConfig: true
  # 打印启动标语
  banner:
    enable: true
  # 向量数据库
  datasource:
    vector:
      url: jdbc:postgresql://localhost:5432/postgres?currentSchema=luck_report_vector
      username: postgres
      password: root
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 5
